version: '3.7'
services:
  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: socializer
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - db
  php:
    environment:
      PHP_IDE_CONFIG: "serverName=docker-server"
    container_name: php
    image: php:fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/app:cached
      - ./docker/logs/app:/var/www/app/var/log:cached
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - db
      - web
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/log/nginx:cached
      - ./:/var/www/app:cached
    networks:
      - web
#  node:
#    image: node:13-alpine
#    container_name: node
#    ports:
#      - 8080:8080
#    volumes:
#      - ./:/app
#    working_dir: /app
#    tty: true

networks:
  db:
  web: